// <auto-generated />
using System;
using Hospital_Patient_Intake_Scheduling_API_604._23E.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital_Patient_Intake_Scheduling_API_604._23E.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$SHe0o6p9b8o4fIkOpti/W.U6Jm/mFO61RT1ZVGmEDHqAQfzI8tCcW",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$Et32zOFek1KeOY0922fxZebD0CCk1.XFXdCoZ7aUstXPOWAglLfbm",
                            Role = "Receptionist",
                            Username = "receptionist"
                        });
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Doctor", b =>
                {
                    b.HasBaseType("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.User");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Email")
                                .HasColumnName("Doctor_Email");

                            t.Property("Name")
                                .HasColumnName("Doctor_Name");

                            t.Property("PhoneNumber")
                                .HasColumnName("Doctor_PhoneNumber");
                        });

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$lkrIIvWua/cHhdYzD.0zTeL7KOjhI/W9aZIjlAoH0Gm1Ofh3./E3G",
                            Role = "Doctor",
                            Username = "hasan",
                            Email = "hasan.ahmadov@xestexanam.az",
                            IsActive = true,
                            Name = "Dr. Hasan Ahmadov",
                            PhoneNumber = "+994777777777",
                            Specialty = "Cardiology"
                        });
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Patient", b =>
                {
                    b.HasBaseType("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasDiscriminator().HasValue("Patient");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$piebLk58yPt48p.36YS2bu5UorEKRocXt2sXo0wfaY11cXuuqGjA2",
                            Role = "Patient",
                            Username = "sevinc",
                            Address = "Ahmadli",
                            Age = 19,
                            CreatedAt = new DateTime(2025, 11, 19, 18, 2, 34, 679, DateTimeKind.Utc).AddTicks(8816),
                            Email = "sevinc@gmail.com",
                            Name = "Sevinc Abbasova",
                            PhoneNumber = "+994555555555",
                            Symptoms = "Headache, nausea, dizziness",
                            UpdatedAt = new DateTime(2025, 11, 19, 18, 2, 34, 679, DateTimeKind.Utc).AddTicks(8821)
                        });
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Appointment", b =>
                {
                    b.HasOne("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
