// <auto-generated />
using System;
using Hospital_Patient_Intake_Scheduling_API_604._23E.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Patient_Intake_Scheduling_API_604._23E.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$TiIwTJWF9Ko44OG6fW3fSOHoDTPBlDP4UsUFOupTdc0twTxWrxifu",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$TTlniSi62L5z8LzMiPaqwOhbjdWouvA6kXQdgYlVB74tjUNWfyhaq",
                            Role = "Receptionist",
                            Username = "receptionist"
                        });
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Doctor", b =>
                {
                    b.HasBaseType("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.User");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Email")
                                .HasColumnName("Doctor_Email");

                            t.Property("Name")
                                .HasColumnName("Doctor_Name");

                            t.Property("PhoneNumber")
                                .HasColumnName("Doctor_PhoneNumber");
                        });

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$RhmBBnejRUcFB2lQ6SEJau3xeMHiS./GeXlFg/yOA.LrK8oAbOSMG",
                            Role = "Doctor",
                            Username = "hasan",
                            Email = "hasan.ahmadov@xestexanam.az",
                            IsActive = true,
                            Name = "Dr. Hasan Ahmadov",
                            PhoneNumber = "+994777777777",
                            Specialty = "Cardiology"
                        });
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Patient", b =>
                {
                    b.HasBaseType("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Patient");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$TyJGXoD4tD41nXVBsGqMqeqm0B.NJcII4DwDtHymWayCBztXkGi.6",
                            Role = "Patient",
                            Username = "sevinc",
                            Address = "Ahmadli",
                            Age = 19,
                            CreatedAt = new DateTime(2025, 11, 19, 15, 32, 0, 723, DateTimeKind.Utc).AddTicks(5164),
                            Email = "sevinc@gmail.com",
                            Name = "Sevinc Abbasova",
                            PhoneNumber = "+994555555555",
                            Symptoms = "Headache, nausea, dizziness",
                            UpdatedAt = new DateTime(2025, 11, 19, 15, 32, 0, 723, DateTimeKind.Utc).AddTicks(5169)
                        });
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Appointment", b =>
                {
                    b.HasOne("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_Patient_Intake_Scheduling_API_604._23E.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
